### ISSUE TITLE
UniSkinAPI not implemented correctly

### ISSUE THREAD

**Issue by RecursiveG** [printempw/blessing-skin-server#9]
When accessing `https://skin.prinzeugen.net/rg.json`, I get the following response:

```
{
    "cape": "",
    "skins": {
        "default": "c94c049e5fd3911107d91db5d938aeca45ce307cb94cf3c17d92303f2c365739",
        "slim": ""
    },
    "username": "rg"
}
```

The correct name for `username` field is `player_name`.
And there should be a `model_preference` field indicating the textures to be loaded.
Otherwise UniSkinMod assumes that the player don't want to load any skins.

**Comment by prinsss** [comment]
Well, that JSON profile is not an implementation of UniSkinAPI.

The author of CustomSkinLoader have put forward another JSON API, and `https://skin.prinzeugen.net/rg.json` is a implementation of it.

It is a feature that Blessing Skin Server supports both UniSkinAPI and CSL API. Users can switch API preference of site in options page.

The default API of skin.prinzeugen.net is CSL API, because UniSkinMod hasnt been in development for a long time, and the mod didn't support alex model although model is declared in JSON profile that implemented USM API.

Sorry but CSL is more complete than USM NOW, and with the consideration for users, I chose CSL as default API.

You can also access `https://skin.prinzeugen.net/usm/rg.json` to get your JSON profile that implemented full UniSkinAPI.

**Comment by prinsss** [comment]
Here the defination of CSL API is: https://github.com/xfl03/CustomSkinLoaderAPI/blob/master/CustomSkinAPI/CustomSkinAPI_en.md

Well, it is only a simplified defination of UniSkinAPI. 

Glad to know that you began to work on UniSkinMod again :)

**Comment by RecursiveG** [comment]
Thank you for the reply.
And new versions of UniSkinMod (1.9 support) has [released](https://github.com/RecursiveG/UniSkinMod/releases).

**Comment by prinsss** [comment]
Awesome!
I will add an option for users of changing their API preference in next update. The suffix `/usm` is awful, right? :)

BTW, could you add a link of Blessing Skin Server's [release thread](http://www.mcbbs.net/thread-552877-1-1.html)? Users may be stuck when see the unknown word `Blessing Skin Server皮肤站链接` in your thread.

**Comment by RecursiveG** [comment]
No, you don't need to add that option. I've already added the suffix into the default configuration of USM. Making this change will cause confusion and increase incompatibility. Please don't do that. Just leave it there. That's fine.

BTW: Isn't that can be changed via rewrite rules?

**Comment by prinsss** [comment]
Okay ；)

**Comment by prinsss** [comment]
Of course, it is implemented by using rewrite rules. 

The developer of CSL suggested to use suffix like `usm` and `csl` to get JSON profile in which format forcibly in case that website manager use one as default but the user wanna use another mod.

Any suggestion?

**Comment by RecursiveG** [comment]
Adding suffix is good. It makes things clear. I think there are little meaning to have a "default" API, since both USM and CSL support URI customization.

**Comment by prinsss** [comment]
Well, you are right .
